SEVERITY_WEIGHT = 0.35
CONFIDENCE_WEIGHT = 0.20
ASSET_CRITICALITY_WEIGHT = 0.20
USER_PRIVILEGE_WEIGHT = 0.10
THREAT_CONTEXT_WEIGHT = 0.10
MITRE_CONTEXT_WEIGHT = 0.05

SEVERITY_SCORES = {
    "low": 25,
    "medium": 50,
    "high": 75,
    "critical": 100,
}

PRIVILEGE_SCORES = {
    "none": 25,
    "standard": 50,
    "privileged": 100,
}